### ISSUE TITLE
Make fjall::WriteTransaction Send

### ISSUE THREAD

**Issue by beckend** [fjall-rs/fjall#65]
https://docs.rs/fjall/latest/fjall/struct.WriteTransaction.html

It's hard to use across threads in async context, internally it's using a Mutex, is it not possible to implement the Send bound?

It makes it easier to wrap the API.

**Comment by marvin-j97** [comment]
I think - and maybe someone can correct me on this - this is not possible with std Mutexes, because they need to be unlocked on the same thread that locked them (https://github.com/rust-lang/rust/issues/23465). I don't understand why, but it's a limitation of the std locks. One way to get around this would be using parking_lot's `send_guard` feature (https://github.com/Amanieu/parking_lot/issues/197), I guess.

Currently, the transactions are single-writer transactions, so each transaction holds the global write lock it gets from the keyspace. With concurrency control (SSI, https://github.com/fjall-rs/fjall/issues/55), the lock would not need to be held before the transaction is committed, so I think SSI transactions would be Send-able.

**Comment by beckend** [comment]
Mutex works with the underlying data. If T is Send, so is the Mutex.

**Comment by marvin-j97** [comment]
> Mutex works with the underlying data. If T is Send, so is the Mutex.

Yeah you are right, I meant MutexGuard specifically, because the WriteTx holds a guard, not a Mutex.

**Comment by marvin-j97** [comment]
With #55 transactions should become Send because they will not contain a lock guard.

**Comment by marvin-j97** [comment]
Should work for SSI transactions, implemented in https://github.com/fjall-rs/fjall/pull/79
